[package]
name = "echo-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
echo-bridge.workspace = true
echo-catalog.workspace = true
echo-core.workspace = true

[lints]
workspace = true
