# The immediately preceding Cargo invocation binds this directory to the
# static library CMake links. Historical test/lint caches are not candidates.
foreach(variable IN ITEMS ECHO_CARGO_BUILD_RECEIPT ECHO_CXXBRIDGE_INCLUDE_DIRECTORY)
    if(NOT DEFINED ${variable} OR "${${variable}}" STREQUAL "")
        message(FATAL_ERROR "sync_cxxbridge_headers requires ${variable}")
    endif()
endforeach()
file(READ "${ECHO_CARGO_BUILD_RECEIPT}" receipt)
string(JSON generated_include_directory GET "${receipt}" include_directory)
if(NOT EXISTS "${generated_include_directory}/echo-desktop-bridge/src/lib.rs.h")
    message(FATAL_ERROR "missing generated desktop bridge header from this Cargo build")
endif()
file(MAKE_DIRECTORY "${ECHO_CXXBRIDGE_INCLUDE_DIRECTORY}")
file(COPY "${generated_include_directory}/" DESTINATION "${ECHO_CXXBRIDGE_INCLUDE_DIRECTORY}")
message(STATUS "Synced Cargo cxxbridge headers into ${ECHO_CXXBRIDGE_INCLUDE_DIRECTORY}")
